### ISSUE TITLE
UniFi Secure Gateway Setup

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-computer-networking#6]
Official guide: https://dl.ubnt.com/guides/UniFi/USG_QSG.pdf

Useful video:
[![image](https://user-images.githubusercontent.com/194400/102000475-d2fb7300-3cdf-11eb-9f3d-96721785e9db.png)](https://youtu.be/L117QGGtvDo)
https://youtu.be/L117QGGtvDo

**Comment by nelsonic** [comment]
Trying to follow these instructions to adopt the USG:
https://help.ui.com/hc/en-us/articles/236281367-UniFi-Adopting-a-USG-into-an-Existing-Network
![image](https://user-images.githubusercontent.com/194400/102022420-9cc10080-3d7e-11eb-8139-d71c9e08b614.png)

Getting the following on the management page: https://192.168.1.1/#/manage/main
![image](https://user-images.githubusercontent.com/194400/102022411-9468c580-3d7e-11eb-94b2-1ee2d8691501.png)

**Comment by nelsonic** [comment]
According to the instructions, we need to put our MEO router into "Bridge Mode" in order to configure the USG ...
Going to follow the steps outlined in this: https://pplware.sapo.pt/tutoriais/router-fiber-gateway-meo-segundo-router

**Comment by nelsonic** [comment]
Plugged into the MEO Router, visit: http://192.168.1.254/index.html#/gui/lan/home

**Comment by iteles** [comment]
Works amazingly!

**Comment by nelsonic** [comment]
@iteles indeed. Glad it's working. But definitely not yet _documented_ ... 🙄

**Comment by nelsonic** [comment]
I'm getting **`320Mbps`** throughout the house now.
![image](https://user-images.githubusercontent.com/194400/102142155-d6b30500-3e59-11eb-9817-50104fadf8ce.png)

Still do be done: https://github.com/dwyl/home/issues/133
